server:
  port: 8080
#  ssl:
#    key-store: ssl.p12
#    key-store-type: PKCS12
#    key-store-password: m960326
#    key-alias: spring
#    trust-store: trustStore.ts
#    trust-store-password: m960326
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 120MB
