server:
  port: 443
  ssl:
    enabled: true
    key-store: cert.jks
    key-store-type: JKS
    key-store-password: m960326
    key-alias: spring
#    trust-store: trustStore.ts
#    trust-store-password: m960326
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 120MB
